### ISSUE TITLE
Is it possible to use columns in slides?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#24] opened 2020-07-22 16:00 UTC
I have a tendency in slides to sometimes have a picture with some text at the side, or two bits of text side-by-side. I have tried two methods that work in beamer in `makecourse`. 

This is the method I would usually use:

```
\begin{frame}{Egypt}
  \begin{columns}
    \begin{column}{0.7\textwidth}
      \begin{itemize}
        \item The classical Greeks believed maths was invented in Egypt.
        \item However, we have very little evidence of Egyptian maths; only a few papyrus survive.
      \end{itemize}
    \end{column}
    \begin{column}{0.3\textwidth}
        \includegraphics[width=\textwidth]{rhind-bm.jpg} {\tiny Rhind Papyrus. \textcopyright~Trustees of the British Museum.}
    \end{column}
  \end{columns}
\end{frame}
```

And this is another that works okay in beamer:

```
\begin{frame}{Egypt}
    \begin{multicols}{2}%
        \begin{itemize}
            \item The classical Greeks believed maths was invented in Egypt.
            \item However, we have very little evidence of Egyptian maths; only a few papyrus survive.
        \end{itemize}  \columnbreak
        \includegraphics[width=0.4\textwidth]{rhind-bm.jpg} {\tiny Rhind Papyrus. \textcopyright~Trustees of the British Museum.}
    \end{multicols}
\end{frame}
```

However, neither of these do anything with `makecourse`. The HTML version is pictures under text, which is fine I suppose as this is not a slides display format. The Slides version is also pictures under text, and off the bottom of the screen. And the PDF version is picture below slides and goes over more than one page. The best I can get is to tell `config.yml` that this is a `chapter` and then I get the HTML version with pictures below text and the PDF is rendered using beamer as I expect to see it. 

Is there a way to get a two-column (side-by-side) slide  in the PDF and Slides display methods using the `slides` type in `makecourse`?

**Comment by extigy** [comment] 2020-07-23 08:31
Beamer slides are unfortunately one of the things that still requires a lot of work, particularly when integrating the output into reveal.js formatted slides. Much of our efforts so far with regards to slides have been targeted towards handling markdown source.

I will try revisiting the whole beamer slides process soon and hopefully improve the output. At the very least, I think the downloadable PDF version of beamer slides should be the version produced by pdflatex, rather than the version produced by coursebuilder, simply due to the principle of least surprise.

**Comment by extigy** [comment] 2020-07-23 16:43
Commit 867ffaa8b0ce4066cd24e97b7201f63dfe4da81e makes it so that the PDF versions of beamer slides are just the output from pdflatex, so that there is at least one version of the slides that look as the author intended.

Commit 3f668b4972d54e35072b0c57c4a3fbe1f6fd90ab makes it so that `\begin{colums}` is rendered as a flexbox in HTML output, hopefully making columns work better in that mode.

There is probably still much beamer functionality that is not yet implemented but I will close this particular issue with the intention to add functionality as requested/required.

**Closed by extigy** 2020-07-23 16:43 UTC

**Comment by prowlett** [comment] 2020-07-23 22:51
This is great, and so fast, thank you. However, I tried it and hit a couple of snags. (I'm new to GitHub and unsure whether it is better to raise a new issue or respond here?)

1. Now makecourse produces columns in the HTML output and the PDF looks like I expect from Beamer. However, there is no longer a 'Slides' view (the HTML slide presentation mode). Is that intended? I'm not sure how much I need all three, but it was there and now it isn't.
2. The HTML generated with the columns seems to work well visually, but the HTML does not validate. This is because it produces a structure like `<p><p><div class="beamer-columns"><div class="beamer-column" style="..."></div><div class="beamer-column" style="..."></div></div></p></p>`. The outer `p` tags should be removed or made into `div`s. In fact, a slide without columns is still contained within a `p`, which is bad if what the slide holds doesn't sit within a `p` (e.g. `<ul>`).

**Comment by extigy** [comment] 2020-07-24 08:36
No problem, thanks for the feature request.

1. This was intended, at least for the moment. It view was intended for markdown slides where the native output is HTML slides. It makes less sense to keep both that and the PDF view for beamer slides where the native output is already a PDF. The view might come back later as an opt-in, once beamer slides are able to be converted into the reveal.js format a little better.

2. Ah yes, you're right. I've noticed plasTeX can be trigger happy with `<p>` tags (it likes making empty ones too, which are filtered out). I'm not sure if this is due to some override I have made or a problem with the plasTeX package. I will add a new issue to remind me to investigate.
